### ISSUE TITLE
To do list for milestone 1

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/DSCI_532_Group18_Allstars#1]
- [x] Create repo 
- [x] Add license in the repo
- [x] Teamwork contract, Code of Conduct, Contribution Guidelines
- [x] Select dataset
- [x] Proposal writeup 
- [x] Description of the app and sketch
- [x] Optional part
- [x] Release
- [x] Submission on Canvas

**Comment by deepaksidhu** [comment]
Milestone 1 tasks are completed.
