### ISSUE TITLE
Milestone 2 to do list

### ISSUE THREAD

**Issue by williamxu7** [UBC-MDS/DSCI_532_Group18_Allstars#13]
- [x] Meeting Thursday at 7pm
- [x] GitHub folder structure (include raw, processed data folder), proposal goes to the doc, reports folder, yaml file
- [x] Interactive Dash app (plots: world map, bar chart, error bar)
- [x] Reflection (markdown file  -> doc folder in repo)
- [x] Deployment on Heroku
- [x] (Optional) Improve README 
- [x] Release, submission HTML link

**Comment by zmerpez** [comment]
- [x]  include the link to your deployed dashboard clearly visible near the top of your README.

**Comment by williamxu7** [comment]
Close this Milestone 2 to do list. Amazing work, everyone!
